site_name: Tôi luyện bản thân - Khu học mở  
site_description: Luyện bản thân, chắc vậy (đại khái là self-improvement nói chung bla bla).
site_author: duykhanh471  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - 'Khởi điểm': 
    - 'Mở đầu': 'index.md'
    - 'Động lực': 'dong-luc.md'
  - 'Phát triển bản thân':
    - 'Đọc sách': 'doc-sach.md'
    - 'Tự học': 'tu-hoc.md'
    - 'Ăn uống & Ngủ nghỉ': 'eat-sleep.md'
    - 'Tập thể dục': 'the-duc.md'
  - 'Hướng dẫn':
    - 'Hướng dẫn chính': 'guide.md'
  - 'Thói quen':
    - 'Thói quen nguyên tử': 'tiny-habit.md'
    - '30 ngày phát triển': '30ngay.md'    
    - 'Những thói quen hay': 'thoi-quen.md'
  - 'Kĩ năng':
    - 'Quản lý tài chính': 'tai-chinh.md'
    - 'Ghi nhớ mọi thứ': 'ghi-nho.md'
    - 'Trở thành người nghe': 'nguoi-nghe.md'
    - 'Grooming Guide': 'grooming.md'
    - 'Còn gì khác?': 'other.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'tai-nguyen.md'


theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false
