site_name: Tôi luyện bản thân - Khu học mở  
site_description: Luyện bản thân, chắc vậy (đại khái là self-improvement nói chung bla bla).
site_author: duykhanh471  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - 'Bản thân': 
    - 'Mở đầu': 'index.md'
    - 'Hướng dẫn chính': 'guide.md'
    - '30 ngày phát triển': '30ngay.md'
    - 'Động lực': 'dong-luc.md'
  - 'Sức khỏe tinh thần':
    - 'Đọc sách': 'doc-sach.md'
  - 'Kiến thức':
    - 'Học tập': 'hoc-tap.md'
  - 'Sức khỏe thể chất':
    - 'Ăn uống': 'diet.md'
    - 'Ngủ': 'sleeping.md'
  - 'Thói quen':
    - 'Những thói quen hay': 'thoi-quen.md'
  - 'Kĩ năng':
    - 'Quản lý tài chính': 'tai-chinh.md'


theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

plugins:
  - open-in-new-tab
  
extra:
  generator: false
